[project]
name = "a-s-p"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a>=0.44",
    "a2a-sdk>=1.0.2",
    "fasta2a[pydantic-ai]>=0.6.1",
    "google-api-core>=2.30.3",
    "googleapis-common-protos>=1.75.0",
    "gradio>=6.19.0",
    "httpx>=0.28.1",
    "httpx-sse>=0.4.3",
    "jinja2>=3.1.6",
    "json-rpc>=1.15.0",
    "natsort>=8.4.0",
    "numpy>=2.4.3",
    "openai-agents>=0.17.2",
    "packaging>=26.2",
    "pandas>=3.0.1",
    "proto-plus>=1.28.0",
    "protobuf>=7.34.1",
    "pydantic>=2.13.4",
    "sse-starlette>=3.4.2",
    "starlette>=1.0.0",
    "torch>=2.12.1",
    "transformers>=5.12.1",
    "uvicorn>=0.46.0",
]
